# Generated by Django 4.1.2 on 2024-06-06 05:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Yangiliklar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rasm", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("title", models.TextField()),
                ("text", ckeditor_uploader.fields.RichTextUploadingField()),
                ("sana", models.DateTimeField()),
            ],
            options={
                "ordering": ("-sana",),
            },
        ),
    ]
